## MEDICAL INSURANCE 

#### LOAD LIBRARIES

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

#### IMPORT DATASET

In [2]:
df = pd.read_csv('insurance.csv')

In [3]:
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

#### NULL VALUE CHECKING

In [4]:
df['charges'].unique()

array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603])

In [5]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

#### CHECK DUPLICATES 

In [6]:
df.duplicated().sum()

1

In [7]:
df=df.drop_duplicates()

#### SPLIT X AND Y

In [8]:
x = df.drop('charges', axis=1)

In [9]:
y = df.charges

#### ENCODE CATEGORICAL COLUMNS AND SCALE NUMERICAL COLUMNS

In [10]:
catgrcl_colms= ['sex','smoker','region']
numbr_cols= ['age','bmi','children']

In [11]:
preprocessor =ColumnTransformer(transformers=[('num', StandardScaler(),numbr_cols),
                                            ('cat', OneHotEncoder(drop='first'), catgrcl_colms)])

x= preprocessor.fit_transform(x)

#### TRAIN TEST SPLIIT

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

#### BUILD ANN MODEL

In [13]:
model = Sequential([
    Dense(64, activation='relu', input_shape = (x_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)])

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


#### COMPILE MODEL

In [14]:
model.compile(optimizer='adam', loss='mse',metrics=['mae'])

#### TRAIN THE MODEL

In [15]:
history = model.fit(
    x_train,
    y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.1,
    verbose=1)

Epoch 1/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 317684512.0000 - mae: 13299.7402 - val_loss: 316772608.0000 - val_mae: 12730.5615
Epoch 2/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 299799840.0000 - mae: 12966.7793 - val_loss: 316698016.0000 - val_mae: 12727.8652
Epoch 3/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 305128800.0000 - mae: 13072.9238 - val_loss: 316520032.0000 - val_mae: 12721.5957
Epoch 4/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - loss: 280342944.0000 - mae: 12612.4619 - val_loss: 316166560.0000 - val_mae: 12709.5039
Epoch 5/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - loss: 301648160.0000 - mae: 13080.8555 - val_loss: 315538176.0000 - val_mae: 12688.4639
Epoch 6/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - loss: 321874528.0000 - mae: 13417.8027 - val_loss: 314489344.0000 - val_mae: 12654.1064
Epoch 7/100
31/31 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - loss: 333532736.0000 - mae: 13569.9922 - val_loss: 312898016.0000 - val_mae: 12602.8525
Epoch

#### EVALUATE MODEL

In [16]:
loss, mae = model.evaluate(x_test, y_test)
print("Mean Absolute Error:", mae)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 65036504.0000 - mae: 5801.8662
Mean Absolute Error: 5573.52783203125


#### MAKE PREDICTION

In [17]:
pred = model.predict(x_test[:5])
print(pred)
print(y_test[:5].values)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[[ 8694.272]
 [ 7776.013]
 [14889.768]
 [27289.596]
 [13142.401]]
[ 8688.85885  5708.867   11436.73815 38746.3551   4463.2051 ]


#### MODEL SUMMARY

In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,069 (31.52 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,380 (21.02 KB)

#### MODEL SAVING

In [19]:
model.save('med_ins_ann.keras')

In [21]:
x_train.shape[1]

8

In [22]:
x_train

array([[-1.15549877, -1.00906256, -0.90923416, ...,  0.        ,
         0.        ,  0.        ],
       [-1.29795825, -0.80654334,  0.75035092, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.91016372,  1.12517847,  0.75035092, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [-1.36918799, -1.42066033, -0.07944162, ...,  0.        ,
         0.        ,  1.        ],
       [-0.08705265, -0.43676128,  1.58014347, ...,  0.        ,
         0.        ,  1.        ],
       [-0.30074188,  0.85214648,  0.75035092, ...,  0.        ,
         1.        ,  0.        ]])